language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script: make && make testci

#before_install:
#  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - codecov
